files:
    upload:
        path: /Users/zhangjixin/Documents/vueProject/files/
mybatis:
    mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 9090
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Zhangjx123
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8
        username: root
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
#            如果是想要不限制文件上传的大小，那么就把两个值都设置为-1就行啦
